name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: make application.yml
      run: |
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        
    - name: Grant execute permission for gradlew and build
      run: |
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew -x test build
      
      # Docker 이미지 Build (2)
    - name: docker image build
      run: | 
        sudo docker rmi spring-docker
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-docker --pull --no-cache . #image명 기입


    # DockerHub Login (3)
    - name: docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker Hub push (4)
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-docker

    # AWS EC2 Server Connect & Docker 명령어 실행 (8)
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }} # pem 키
        
        # 도커 작업
        script: |
          sudo docker stop spring-docker
          sudo docker rm spring-docker
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring-docker
          sudo docker run -it -d -p 8080:8080 --name spring-docker ${{ secrets.DOCKER_USERNAME }}/spring-docker


  # time
  current-time:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00" # 기준이 UTC이기 때문에 한국시간인 KST를 맞추기 위해 +9시간 추가
  
      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
        shell: bash
